export const header_container: string;
export const nav_container: string;
export const name_logo_container: string;
export const header_img: string;
export const title_container: string;
export const header_name_1: string;
export const header_name_2: string;
export const nav_list: string;
export const avatar_container: string;